before:
  hooks:
    - make headers

builds:
  - id: grace
    main: .
    binary: grace
    ldflags:
      - "-linkmode external -s -w -extldflags '-fno-PIC -static'"
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS="-Iheaders/include"
    goos:
      - linux
    goarch:
      - "amd64"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

archives:
  - format: binary
    name_template: "{{ .Binary}}-{{ .Os }}-{{ .Arch }}"

release:
  prerelease: auto
  github:
    owner: liamg
    name: grace
