name: tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          cache: true
      - name: Run tests
        run: sudo apt install -y musl-tools && make test
